// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5GNFyKjCtDGgUktGjjzM9skSSdeFCz4',
    appId: '1:522005934698:web:ec3a7af999bc6192489013',
    messagingSenderId: '522005934698',
    projectId: 'dass-team-15',
    authDomain: 'dass-team-15.firebaseapp.com',
    databaseURL: 'https://dass-team-15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dass-team-15.appspot.com',
    measurementId: 'G-62KSDEZX12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBBEVKSIvaG2ZrQQTzEYs3nhEwcuU0N9Q',
    appId: '1:522005934698:android:6970e13b3a5f963e489013',
    messagingSenderId: '522005934698',
    projectId: 'dass-team-15',
    databaseURL: 'https://dass-team-15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dass-team-15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWc7iSniD4rXQhv9ciYqEzmsdHnxnw-gY',
    appId: '1:522005934698:ios:5969255a7f975bfe489013',
    messagingSenderId: '522005934698',
    projectId: 'dass-team-15',
    databaseURL: 'https://dass-team-15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dass-team-15.appspot.com',
    iosClientId: '522005934698-3l9o5657a32poupvqkc2mm1c2ei64m96.apps.googleusercontent.com',
    iosBundleId: 'com.example.multipleScreens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWc7iSniD4rXQhv9ciYqEzmsdHnxnw-gY',
    appId: '1:522005934698:ios:5969255a7f975bfe489013',
    messagingSenderId: '522005934698',
    projectId: 'dass-team-15',
    databaseURL: 'https://dass-team-15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dass-team-15.appspot.com',
    iosClientId: '522005934698-3l9o5657a32poupvqkc2mm1c2ei64m96.apps.googleusercontent.com',
    iosBundleId: 'com.example.multipleScreens',
  );
}
